### ISSUE TITLE
Support Solr 5.2+

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/solr-typo3-plugin#3]
Currently the Solr plugin only support Solr up to v5.1. To support newer versions we need to make changes. This article might be helpful:
http://lucidworks.com/blog/2015/05/15/custom-security-filtering-solr-5/

**Comment by irnnr** [comment]
The `RuleBasedAuthorizationPlugin` mentioned in the Solr 5.5 release notes might be interesting to look at. Maybe we can find something that we can re-use to update the plugin for current Solr versions.

https://mail-archives.apache.org/mod_mbox/www-announce/201602.mbox/%3CCAL8PwkYkp%2BqrHrL=XNwgswtkt5w9w59T5NhdxPzBuj7prpsX1Q@mail.gmail.com%3E

**Comment by irnnr** [comment]
source: https://github.com/apache/lucene-solr/blob/master/solr/core/src/java/org/apache/solr/security/BasicAuthPlugin.java

**Comment by irnnr** [comment]
never mind, it's only meant for general access to Solr and it's collections, not for checking access on a document level
https://cwiki.apache.org/confluence/display/solr/Rule-Based+Authorization+Plugin

**Comment by timohund** [comment]
We've published version 1.6.1 (For Apache Solr 6.1.0) 

https://github.com/TYPO3-Solr/solr-typo3-plugin/releases/tag/release-1_6_1
